### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by AechtRob** [Nosiphus/atlantis#4]
Is there an chance of being able to reduce the generation of ores? The aquamarine ore is especially wayyyyyy too common in caves.

Also, I don't understand this in the config:

general {
    # Atlantis ID
    # Min: -1000
    # Max: 1000
    I:"Atlantis ID"=324987
 
The value there as default is not between -1000 and 1000 (!) - what is the dimension ID that this mod is going to use?
Thanks.

**Comment by Mysticpasta1** [comment]
I will work out something for the ore and thank you for telling me about that config issue I didn't notice it.

**Comment by Mysticpasta1** [comment]
This is now solve in v2.2
